FROM shyamsalimkumar/intellij-idea:v15.0.1

# Install Java 6,7
RUN sed 's/main$/main universe/' -i /etc/apt/sources.list && \
    apt-get update && apt-get install -y software-properties-common && \
    add-apt-repository ppa:webupd8team/java -y && \
    apt-get update && \
    echo \
        oracle-java6-installer \
        oracle-java7-installer \
        shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections && \
    apt-get install -y \
        oracle-java6-installer \
        oracle-java7-installer \
        libxext-dev libxrender-dev libxtst-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /tmp/*

# Install Scala and SBT
RUN echo 'Installing Scala' && \
    wget http://www.scala-lang.org/files/archive/scala-2.10.6.deb -O /tmp/scala-2.10.deb && \
    dpkg -i /tmp/scala-2.10.deb && \
    apt-get update && \
    apt-get install && \
    echo 'Installing SBT' && \
    wget https://bintray.com/artifact/download/sbt/debian/sbt-0.13.9.deb -O /tmp/sbt.deb && \
    dpkg -i /tmp/sbt.deb && \
    apt-get update && \
    apt-get install sbt && \
    rm -rf /tmp/*
